@startuml
title Luong 2 - Tra cuu va loc khoa hoc

participant "Nhan vien hoc vu" as User
participant "Course List View" as View
participant "CourseController" as Ctrl
participant "CourseService" as Svc
participant "CourseRepository" as Repo

User -> View : Chon Level va nhap hoc phi toi da
View -> Ctrl : GET /course/list?level=Intermediate&maxFee=6000000
Ctrl -> Svc : searchCourses("Intermediate", 6000000)
Svc -> Repo : findAll()
Repo --> Svc : List<Course>
Svc --> Ctrl : Danh sach da loc
Ctrl --> View : model.addAttribute("courses", list)
View --> User : Hien thi bang khoa hoc

@enduml
