@startuml
title Luong 1 - Tai layout va dieu huong

participant "Nhan vien hoc vu" as User
participant "Browser" as Browser
participant "HomeController" as Home
participant "CourseController" as CourseCtrl
participant "Main Layout" as Layout

User -> Browser : Truy cap trang chu
Browser -> Home : GET /
Home --> Browser : redirect:/course/list
Browser -> CourseCtrl : GET /course/list
CourseCtrl --> Browser : Render course/list
Browser -> Layout : Nap layout/main-layout.html
Layout --> User : Header + Navbar + Content

@enduml
